export const authActions = {
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  AUTH_REGISTER__ERROR: 'AUTH_REGISTER__ERROR',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGIN__SUCCESS: 'AUTH_LOGIN__SUCCESS',
  AUTH_LOGIN__ERROR: 'AUTH_LOGIN__ERROR',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
};
